---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-front
  template:
    metadata:
      labels:
        app: web-front
    spec:
      containers:
        - name: web-front
          image: 236747833953.dkr.ecr.ap-northeast-2.amazonaws.com/web-front:29
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ap-northeast-2-ecr-secret
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: web-front
spec:
  selector:
    app: web-front
  ports:
    - name: http
      port: 3000
      targetPort: 3000
